export interface EmojiEntry {
  emoji: string;
  category: string;
  keywords: string;
}

export const EMOJI_CATEGORIES = [
  'Frutas',
  'Verduras',
  'Carnes y pescado',
  'Lácteos y huevos',
  'Pan y bollería',
  'Pasta y arroz',
  'Preparados',
  'Bebidas',
  'Postres y dulces',
  'Deporte',
  'Cuerpo y salud',
  'Cocina y hogar',
  'Otros',
] as const;

type Row = [emoji: string, category: (typeof EMOJI_CATEGORIES)[number], keywords: string];

const ROWS: Row[] = [
  ['🍎', 'Frutas', 'manzana apple'],
  ['🍐', 'Frutas', 'pera pear'],
  ['🍊', 'Frutas', 'naranja mandarina orange tangerine'],
  ['🍋', 'Frutas', 'limon lemon'],
  ['🍌', 'Frutas', 'platano banana'],
  ['🍉', 'Frutas', 'sandia watermelon'],
  ['🍇', 'Frutas', 'uvas grapes'],
  ['🍓', 'Frutas', 'fresa fresas strawberry'],
  ['🫐', 'Frutas', 'arandanos blueberry'],
  ['🍈', 'Frutas', 'melon'],
  ['🍒', 'Frutas', 'cerezas cherry'],
  ['🍑', 'Frutas', 'melocoton durazno peach'],
  ['🥭', 'Frutas', 'mango'],
  ['🍍', 'Frutas', 'pina pineapple'],
  ['🥥', 'Frutas', 'coco coconut'],
  ['🥝', 'Frutas', 'kiwi'],
  ['🍅', 'Verduras', 'tomate tomato'],
  ['🥕', 'Verduras', 'zanahoria carrot'],
  ['🌽', 'Verduras', 'maiz corn'],
  ['🥦', 'Verduras', 'brocoli broccoli'],
  ['🍆', 'Verduras', 'berenjena eggplant'],
  ['🥑', 'Verduras', 'aguacate avocado'],
  ['🌶️', 'Verduras', 'guindilla chile chili picante'],
  ['🫑', 'Verduras', 'pimiento pepper'],
  ['🥒', 'Verduras', 'pepinillo pepino cucumber pickle'],
  ['🥬', 'Verduras', 'lechuga verdura verde cabbage lettuce'],
  ['🧅', 'Verduras', 'cebolla onion'],
  ['🧄', 'Verduras', 'ajo garlic'],
  ['🫚', 'Verduras', 'jengibre ginger'],
  ['🥔', 'Verduras', 'patata papa potato'],
  ['🍠', 'Verduras', 'boniato batata sweet potato'],
  ['🫛', 'Verduras', 'guisantes peas'],
  ['🥜', 'Verduras', 'cacahuete mani peanut'],
  ['🍗', 'Carnes y pescado', 'pollo muslo chicken leg'],
  ['🍖', 'Carnes y pescado', 'carne hueso meat'],
  ['🥩', 'Carnes y pescado', 'filete bistec steak beef'],
  ['🥓', 'Carnes y pescado', 'bacon panceta'],
  ['🍤', 'Carnes y pescado', 'gambas langostinos shrimp prawn'],
  ['🍣', 'Carnes y pescado', 'sushi'],
  ['🦐', 'Carnes y pescado', 'gamba langostino'],
  ['🦞', 'Carnes y pescado', 'langosta lobster'],
  ['🦀', 'Carnes y pescado', 'cangrejo crab'],
  ['🐟', 'Carnes y pescado', 'pescado fish'],
  ['🐠', 'Carnes y pescado', 'pez tropical'],
  ['🐡', 'Carnes y pescado', 'pez globo'],
  ['🐙', 'Carnes y pescado', 'pulpo octopus'],
  ['🦑', 'Carnes y pescado', 'calamar squid'],
  ['🐔', 'Carnes y pescado', 'pollo gallina chicken'],
  ['🐷', 'Carnes y pescado', 'cerdo chancho pig'],
  ['🐮', 'Carnes y pescado', 'vaca ternera cow beef'],
  ['🐑', 'Carnes y pescado', 'cordero oveja sheep'],
  ['🦃', 'Carnes y pescado', 'pavo turkey'],
  ['🥚', 'Lácteos y huevos', 'huevo egg'],
  ['🧀', 'Lácteos y huevos', 'queso cheese'],
  ['🥛', 'Lácteos y huevos', 'leche milk'],
  ['🥤', 'Bebidas', 'refresco soda batido'],
  ['🧃', 'Bebidas', 'zumo jugo juice'],
  ['☕', 'Bebidas', 'cafe coffee'],
  ['🫖', 'Bebidas', 'te infusión tetera'],
  ['🍵', 'Bebidas', 'te matcha'],
  ['🍺', 'Bebidas', 'cerveza beer'],
  ['🍻', 'Bebidas', 'cervezas brindis'],
  ['🥂', 'Bebidas', 'brindis champan'],
  ['🥃', 'Bebidas', 'whisky'],
  ['🍸', 'Bebidas', 'coctel martini'],
  ['🍹', 'Bebidas', 'tropical coctel'],
  ['🧊', 'Bebidas', 'hielo ice'],
  ['🍞', 'Pan y bollería', 'pan bread'],
  ['🥖', 'Pan y bollería', 'baguette barra pan'],
  ['🥐', 'Pan y bollería', 'croissant'],
  ['🥨', 'Pan y bollería', 'pretzel'],
  ['🥯', 'Pan y bollería', 'bagel'],
  ['🥞', 'Pan y bollería', 'panqueques tortitas pancakes'],
  ['🧇', 'Pan y bollería', 'gofres waffles'],
  ['🍕', 'Pasta y arroz', 'pizza'],
  ['🍔', 'Pasta y arroz', 'hamburguesa burger'],
  ['🍟', 'Pasta y arroz', 'patatas fritas fries'],
  ['🌭', 'Pasta y arroz', 'perrito hot dog salchicha'],
  ['🌮', 'Pasta y arroz', 'taco'],
  ['🌯', 'Pasta y arroz', 'burrito'],
  ['🥙', 'Pasta y arroz', 'durum kebab'],
  ['🥪', 'Pasta y arroz', 'sandwich bocadillo'],
  ['🍜', 'Pasta y arroz', 'sopa noodles ramen'],
  ['🍝', 'Pasta y arroz', 'espaguetis pasta spaghetti'],
  ['🍲', 'Pasta y arroz', 'guiso estofado stew'],
  ['🍛', 'Pasta y arroz', 'curry arroz'],
  ['🥟', 'Pasta y arroz', 'empanadilla dumpling gyozas'],
  ['🍱', 'Pasta y arroz', 'bento'],
  ['🍘', 'Pasta y arroz', 'galleta arroz'],
  ['🍙', 'Pasta y arroz', 'onigiri'],
  ['🍚', 'Pasta y arroz', 'arroz rice'],
  ['🫕', 'Pasta y arroz', 'fondue queso'],
  ['🌰', 'Otros', 'castaña chestnut'],
  ['🥗', 'Preparados', 'ensalada salad'],
  ['🥣', 'Preparados', 'bol cereal sopa bowl'],
  ['🍳', 'Preparados', 'huevo frito sarten frying pan'],
  ['🥘', 'Preparados', 'paella cazuela'],
  ['🍿', 'Preparados', 'palomitas popcorn'],
  ['🍯', 'Preparados', 'miel honey'],
  ['🧂', 'Preparados', 'sal salt'],
  ['🧈', 'Preparados', 'mantequilla butter'],
  ['🍦', 'Postres y dulces', 'helado cono ice cream'],
  ['🍧', 'Postres y dulces', 'granizado'],
  ['🍨', 'Postres y dulces', 'copa helado'],
  ['🍩', 'Postres y dulces', 'donut dónut'],
  ['🍪', 'Postres y dulces', 'galleta cookie'],
  ['🎂', 'Postres y dulces', 'tarta cumpleaños'],
  ['🍰', 'Postres y dulces', 'pastel tarta cake'],
  ['🧁', 'Postres y dulces', 'cupcake magdalena'],
  ['🥧', 'Postres y dulces', 'pay pie quiche'],
  ['🍫', 'Postres y dulces', 'chocolate'],
  ['🍬', 'Postres y dulces', 'caramelo golosina'],
  ['🍭', 'Postres y dulces', 'piruleta lollipop'],
  ['🍮', 'Postres y dulces', 'flan pudding'],
  ['🍡', 'Postres y dulces', 'dango brocheta'],
  ['🏋️', 'Deporte', 'pesas gimnasio weightlifting'],
  ['💪', 'Deporte', 'bicep fuerza muscle'],
  ['🏃', 'Deporte', 'correr runner'],
  ['🚴', 'Deporte', 'bicicleta cycling bike'],
  ['🚵', 'Deporte', 'bici montaña mountain'],
  ['🏊', 'Deporte', 'nadar swimming'],
  ['🧘', 'Deporte', 'meditacion yoga'],
  ['🤸', 'Deporte', 'gimnasia cartwheel'],
  ['⛹️', 'Deporte', 'baloncesto basketball'],
  ['🤾', 'Deporte', 'balonmano handball'],
  ['🏄', 'Deporte', 'surf'],
  ['⛷️', 'Deporte', 'esqui ski'],
  ['⛸️', 'Deporte', 'patinaje skating'],
  ['🤺', 'Deporte', 'esgrima fencing'],
  ['🛹', 'Deporte', 'skate monopatín'],
  ['🥇', 'Deporte', 'oro medal'],
  ['🥈', 'Deporte', 'plata medal'],
  ['🥉', 'Deporte', 'bronce medal'],
  ['🏆', 'Deporte', 'trofeo trophy'],
  ['🏅', 'Deporte', 'medalla medal'],
  ['⚖️', 'Cuerpo y salud', 'peso balanza scale'],
  ['📏', 'Cuerpo y salud', 'regla cinta medida ruler'],
  ['📐', 'Cuerpo y salud', 'escuadra'],
  ['🧍', 'Cuerpo y salud', 'persona de pie standing'],
  ['🧎', 'Cuerpo y salud', 'persona rodillas kneeling'],
  ['🦵', 'Cuerpo y salud', 'pierna leg'],
  ['🦶', 'Cuerpo y salud', 'pie foot'],
  ['🫀', 'Cuerpo y salud', 'corazon organo organ'],
  ['🫁', 'Cuerpo y salud', 'pulmones lungs'],
  ['🧠', 'Cuerpo y salud', 'cerebro brain'],
  ['🦴', 'Cuerpo y salud', 'hueso bone'],
  ['❤️', 'Cuerpo y salud', 'corazon heart'],
  ['💛', 'Cuerpo y salud', 'corazon amarillo'],
  ['💚', 'Cuerpo y salud', 'corazon verde'],
  ['💙', 'Cuerpo y salud', 'corazon azul'],
  ['🩺', 'Cuerpo y salud', 'estetoscopio doctor'],
  ['💊', 'Cuerpo y salud', 'pastilla medicina pill'],
  ['💉', 'Cuerpo y salud', 'jeringuilla inyeccion'],
  ['🩸', 'Cuerpo y salud', 'sangre blood'],
  ['🛌', 'Cuerpo y salud', 'cama descanso'],
  ['😴', 'Cuerpo y salud', 'dormir sleeping'],
  ['💤', 'Cuerpo y salud', 'zzz dormir'],
  ['😊', 'Otros', 'sonrisa smile'],
  ['😋', 'Otros', 'rico delicioso yummy'],
  ['🤤', 'Otros', 'babeo hambre'],
  ['😀', 'Otros', 'feliz happy'],
  ['😂', 'Otros', 'risa laugh'],
  ['🤣', 'Otros', 'carcajada'],
  ['😉', 'Otros', 'guino wink'],
  ['🙂', 'Otros', 'sonrisa suave'],
  ['🤔', 'Otros', 'pensar pensar think'],
  ['🤗', 'Otros', 'abrazo hug'],
  ['😅', 'Otros', 'sudor risa'],
  ['🥲', 'Otros', 'sonrisa lagrima'],
  ['😭', 'Otros', 'llorar cry'],
  ['😢', 'Otros', 'triste sad'],
  ['😡', 'Otros', 'enfado angry'],
  ['🤒', 'Otros', 'fiebre enfermo'],
  ['🤕', 'Otros', 'herida'],
  ['😷', 'Otros', 'mascarilla'],
  ['🤢', 'Otros', 'nauseas'],
  ['🤮', 'Otros', 'vomitar'],
  ['⭐', 'Otros', 'estrella star'],
  ['✨', 'Otros', 'brillo sparkles'],
  ['🔥', 'Otros', 'fuego fire'],
  ['🎯', 'Otros', 'diana objetivo target'],
  ['✅', 'Otros', 'check marcado hecho'],
  ['❌', 'Otros', 'cruz error'],
  ['➕', 'Otros', 'mas plus'],
  ['➖', 'Otros', 'menos minus'],
  ['🔄', 'Otros', 'repetir refrescar'],
  ['💯', 'Otros', 'cien perfecto'],
  ['🍽️', 'Cocina y hogar', 'plato cubiertos plate'],
  ['🍴', 'Cocina y hogar', 'tenedor cuchillo cutlery'],
  ['🥄', 'Cocina y hogar', 'cuchara spoon'],
  ['🔪', 'Cocina y hogar', 'cuchillo knife'],
  ['🥫', 'Cocina y hogar', 'lata conserva can'],
  ['⏲️', 'Cocina y hogar', 'temporizador timer'],
  ['📊', 'Cocina y hogar', 'grafica chart stats'],
  ['📈', 'Cocina y hogar', 'grafica subida'],
  ['📉', 'Cocina y hogar', 'grafica bajada'],
  ['📋', 'Cocina y hogar', 'portapapeles lista'],
  ['🗒️', 'Cocina y hogar', 'notas block'],
  ['📅', 'Cocina y hogar', 'calendario calendar'],
  ['⏰', 'Cocina y hogar', 'despertador reloj'],
  ['🕐', 'Cocina y hogar', 'reloj hora'],
  ['🗑️', 'Cocina y hogar', 'papelera borrar trash'],
];

export const EMOJI_CATALOG: EmojiEntry[] = ROWS.map(([emoji, category, keywords]) => ({
  emoji,
  category,
  keywords: keywords.toLowerCase(),
}));

export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return EMOJI_CATALOG.filter(
    (e) =>
      e.emoji.toLowerCase().includes(q) ||
      e.keywords.includes(q) ||
      e.category.toLowerCase().includes(q)
  );
}

export function emojisByCategory(category: string): string[] {
  return EMOJI_CATALOG.filter((e) => e.category === category).map((e) => e.emoji);
}
